name: vulnerability-scan
description: Runs a vulnerability scan on the built image
inputs:
  checkout:
    description: Checkout code before building and scanning image
    required: false
    default: 'true'

  docker-image:
    description: The docker image
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}
      with:
        fetch-depth: 0

    - name: Build image
      shell: bash
      run: docker build -t ${{ inputs.docker-image }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: ${{ inputs.docker-image }}
        format: 'table'
        severity: 'CRITICAL'
        exit-code: '1'
