name: Restore Maven build cache
description: Setup Java and restore the Maven build cache
inputs:
  java-version-file:
    description: The location of the java version file
    required: false
    default: .java-version
  java-distribution:
    description: The distribution to use
    required: false
    default: temurin
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version-file: ${{ inputs.java-version-file }}
        cache: maven

    - name: Restore build
      uses: actions/cache/restore@v4
      with:
        path: '**/target/**'
        key: cache-mvn-build-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          cache-mvn-build-${{ github.run_id }}-
