name: Checkout and setup Node.js
description: Checkout the code and setup Node.js
inputs:
  fetch-depth:
    description: The checkout fetch depth to use.
    required: false
    default: '0'
  node-version-file:
    description: The location of the node version file.
    required: false
    default: .nvmrc
  cache-dependency-path:
    description: The cache location
    required: false
    default: '**/package-lock.json'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}


    - uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: npm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
