name: Service Definition Validator
description: Validates the service definition files to contain the required environment variables.
inputs:
  service-definitions:
    description: 'List of service definition file paths provided as a JSON array string. For example: ["./folder1/service-definition1.yaml", "./folder2/service-definition2"]'
    required: true
  service-type:
    description: 'The type of the service the validation will run for.'
    required: true
    options:
      - 'STATEFUL_PROCESSOR'
      - 'STATELESS_PROCESSOR'
      - 'INPUT_API'
      - 'QUERY_API'
  github-token:
    description: A GitHub token with write access to the repository.
    required: false
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js