name: Print-Topology
description: Print Kafka Stream Processor's topology in mermaid format.
inputs:
  topologyFilePath:
    description: 'Path to the topology file'
    required: false
    default: 'docs/topology/stream.txt'
  processorTopicsOutputFilePath:
    description: 'Path to the file to save extracted list of topics used in the processor.'
    required: false
    default: 'docs/topics/processor-topics.txt'
  readmeFilePath:
    description: 'Path to the README file'
    required: false
    default: 'README.md'
runs:
  using: node16
  main: dist/index.js