name: 'Docker Build'
description: |
  Builds Docker image and pushes it to Google Container Registry.
  The Docker image is being also attested afterwards.

inputs:
  gcloud-auth-staging:
    description: 'GCLOUD_AUTH_STAGING value from secrets'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: true
  gcr-image-name:
    description: 'Google Container Registry Docker image name'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: extenda/actions/setup-gcloud@v0
      id: gcloud
      with:
        service-account-key: ${{ inputs.gcloud-auth-staging }}

    - name: Build and push Docker
      shell: bash
      run: |
        gcloud --quiet auth configure-docker
        IMAGE=eu.gcr.io/extenda/${{ inputs.gcr-image-name }}:${{ github.sha }}
        docker build --provenance=false -t $IMAGE . -f ${{ inputs.dockerfile-path }}
        docker push $IMAGE

    - name: Attest image
      uses: extenda/actions/binary-auth-attestation@v0
      with:
        image-path: eu.gcr.io/extenda/${{ inputs.gcr-image-name }}
        service-account-key: ${{ inputs.gcloud-auth-staging }}
