name: 'Acceptance'
description: 'Acceptance action for Scan&Go and MCPE services'

inputs:
  secret-auth:
    description: 'SECRET_AUTH value from secrets'
    required: true
  gcloud-auth-staging:
    description: 'GCLOUD_AUTH_STAGING value from secrets'
    required: true
  acceptance-username:
    description: 'Acceptance username'
    required: true
  acceptance-postman-collection-path:
    description: 'Path to Postman collection'
    required: false
    default: './mcpe-common/tests/acceptance/scanngo-acceptance.postman_collection.json'
  acceptance-postman-environment-path:
    description: 'Path to Postman environment variables'
    required: false
    default: './mcpe-common/tests/acceptance/scanngo-acceptance.postman_environment.json'
  acceptance-globals-path:
    description: 'Path to globals.json'
    required: false
    default: './mcpe-common/tests/acceptance/globals.json'

runs:
  using: 'composite'
  steps:
    - uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.gcloud-auth-staging }}
        secrets: |
          MCPE_PASSWORD: test_user_mcpe_password
          MCPE2_PASSWORD: test_user_mcpe2_password
          SCANNGO_SHOPPER_PASSWORD: scanngo_shopper_password
          MCPE_SHOPPER_PASSWORD: mcpe_shopper_password
          MCPE_STAFF_PASSWORD: mcpe_staff_password
          ATTENDANT_STAFF_PASSWORD: attedant_staff_password

    - uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.secret-auth }}
        secrets: |
          GITHUB-TOKEN: github-token

    - uses: actions/checkout@v4
      with:
        repository: extenda/mcpe-common
        path: 'mcpe-common'
        token: ${{ env.GITHUB-TOKEN }}

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "./mcpe-common/tests/acceptance/globals.json"
        json: '{"values":[{"key":"scanngo_shopper_username","value":"${{ inputs.acceptance-username }}","enabled":true},{"key":"scanngo_flags_on_username","value":"${{ inputs.acceptance-username }}-on","enabled":true},{"key":"scanngo_rescan_username","value":"${{ inputs.acceptance-username }}-rescan","enabled":true},{"key":"scanngo_shopper_password","value":"${{env.SCANNGO_SHOPPER_PASSWORD}}","enabled":true},{"key":"mcpe_shopper_username","value":"${{ inputs.acceptance-username }}","enabled":true},{"key":"mcpe_shopper_password","value":"${{env.MCPE_SHOPPER_PASSWORD}}","enabled":true},{"key":"attedant_staff_password","value":"${{env.ATTENDANT_STAFF_PASSWORD}}","enabled":true},{"key":"staff_password","value":"${{env.MCPE_STAFF_PASSWORD}}","enabled":true}]}'

    - name: Acceptance tests (scanngo)
      if: ${{ contains(inputs.acceptance-postman-collection-path, 'scanngo-acceptance') }}
      uses: matt-ball/newman-action@master
      with:
        collection: ${{ inputs.acceptance-postman-collection-path }}
        environment: ${{ inputs.acceptance-postman-environment-path }}
        globals: ${{ inputs.acceptance-globals-path }}
        folder: '["Acceptance", "Acceptance - BAS SLP"]'
        bail: true

    - name: Acceptance tests
      if: ${{ !contains(inputs.acceptance-postman-collection-path, 'scanngo-acceptance') }}
      uses: matt-ball/newman-action@master
      with:
        collection: ${{ inputs.acceptance-postman-collection-path }}
        environment: ${{ inputs.acceptance-postman-environment-path }}
        globals: ${{ inputs.acceptance-globals-path }}
        folder: '["Acceptance"]'
        bail: true
