name: 'Build and run tests'

inputs:
  sln-path:
    description: 'Path to the *.sln file'
    required: true
  secret-auth:
    description: 'SECRET_AUTH value from secrets'
    required: true
  gcloud-auth-staging:
    description: 'GCLOUD_AUTH_STAGING value from secrets'
    required: true
  java-distribution:
    description: 'Java distribution to use'
    default: 'temurin'
    required: false
  java-version:
    description: 'Java version to use'
    default: '17'
    required: false
  dotnet-version:
    description: '.NET SDK version to use'
    default: '8'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.secret-auth }}
        secrets: |
          NEXUS_PASSWORD: nexus-password
          NEXUS_USERNAME: nexus-username
          PACT_BROKER_USERNAME: pact-broker-username
          PACT_BROKER_PASSWORD: pact-broker-password

    - name: Determine version
      uses: extenda/actions/conventional-version@v0
      id: semver
      with:
        build-number: ${{ github.run_number }}

    - uses: extenda/actions/opa-policy-test@v0
      with:
        service-account-key: ${{ inputs.gcloud-auth-staging }}

    - name: Add a private NuGet source
      shell: bash
      run: |
        dotnet nuget add source "https://repo.extendaretail.com/repository/nuget-group/" --name "Nexus ExtendaRetail" --username "${{ env.NEXUS_USERNAME }}" --password "${{ env.NEXUS_PASSWORD }}" --store-password-in-clear-text

    - name: Start Sonar Scanner
      uses: extenda/actions/sonar-scanner@v0
      with:
        sonar-host: https://sonarcloud.io
        sonar-scanner: dotnet
        main-branch: ${{ steps.semver.outputs.branch-name-short }}
        service-account-key: ${{ inputs.secret-auth }}

    - name: Build .NET solution
      shell: bash
      run: |
        dotnet build ${{ inputs.sln-path }} --configuration Release /p:Version=${{ steps.semver.outputs.semver }}

    - name: Run tests
      shell: bash
      run: |
        dotnet test ${{ inputs.sln-path }} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        PACT_BROKER_USERNAME: ${{ env.PACT_BROKER_USERNAME }}
        PACT_BROKER_PASSWORD: ${{ env.PACT_BROKER_PASSWORD }}
        PACT_BROKER_BASE_URL: https://pact-broker.retailsvc.com

    - name: Analyze with Sonar
      uses: extenda/actions/sonar-scanner@v0
      with:
        sonar-host: https://sonarcloud.io
        sonar-scanner: dotnet
        main-branch: ${{ steps.semver.outputs.branch-name-short }}
        service-account-key: ${{ inputs.secret-auth }}