name: 'Run database migration'
description: 'Run database migration for the service'
on:
  push:
    branches:
      - main
      - master
inputs:
  IMAGE_NAME:
    description: 'Image name to build and test on'
    required: true
  SECRET_AUTH:
    description: 'Auth for Nexus registry'
    required: true
  GCLOUD_AUTH:
    description: 'GCP Auth'
    required: true
  db_host_secret_name:
    description: 'Key name of the database host in gcp secret manager'
    required: true
  db_port_secret_name:
    description: 'Key name of the database port in gcp secret manager'
    required: true
  db_name_secret_name:
    description: 'Key name of the database name in gcp secret manager'
    required: true
  db_user_secret_name:
    description: 'Key name of the database user in gcp secret manager'
    required: true
  db_pass_secret_name:
    description: 'Key name of the database password in gcp secret manager'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Auth to Nexus npm registry
      uses: extenda/actions/nexus-auth-npm@v0
      with:
        service-account-key: ${{ inputs.SECRET_AUTH }}

    - uses: extenda/actions/setup-gcloud@v0
      id: gcloud
      with:
        service-account-key: ${{ inputs.GCLOUD_AUTH }}

    - name: GCloud configure-docker
      shell: bash
      run: gcloud --quiet auth configure-docker eu.gcr.io

    - name: Build and push db migration image
      shell: bash
      run: |
        docker build -f migration/Dockerfile -t ${{ inputs.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ inputs.IMAGE_NAME }}:${{ github.sha }}

    - name: Attest image
      uses: extenda/actions/binary-auth-attestation@v0
      with:
        image-path: ${{ inputs.IMAGE_NAME }}:${{ github.sha }}
        service-account-key: ${{ inputs.GCLOUD_AUTH }}

    - uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.GCLOUD_AUTH }}
        secrets: |
          DB_HOST: ${{ inputs.db_host_secret_name }}
          DB_NAME: ${{ inputs.db_name_secret_name }}
          DB_USER: ${{ inputs.db_user_secret_name }}
          DB_PASS: ${{ inputs.db_pass_secret_name }}

    - name: Run database migration
      uses: extenda/actions/test-pod@v0
      with:
        service-account-key: ${{ inputs.GCLOUD_AUTH }}
        image: ${{ inputs.IMAGE_NAME }}:${{ github.sha }}
        trim-prefix: true
      env:
        TESTPOD_DB_HOST: ${{ env.DB_HOST }}
        TESTPOD_DB_NAME: ${{ env.DB_NAME }}
        TESTPOD_DB_USER: ${{ env.DB_USER }}
        TESTPOD_DB_PASS: ${{ env.DB_PASS }}
        TESTPOD_DB_PORT: 5432
