name: 'Test OPA Rules'
description: 'Run tests for opa rules'
inputs:
  SECRET_AUTH:
    description: 'GCP Auth'
    required: true
  GCLOUD_AUTH:
    description: 'GCP Auth (Staging)'
    required: false
  system:
    description: '3-letter service name'
    required: true
  service-name:
    description: 'Service name (same as in Styra & GCP)'
    required: true
  policy-type:
    description: |
      The policy you are testing, ingress or app ( default: ingress )
    default: ingress
    required: false
  slack-channel:
    description: Name of the channel to notify failing action
    required: true
  notify-slack-on-fail:
    description: 'If true notifies slack channel specified in secrets in case this workflow fails'
    default: false
    type: boolean
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.SECRET_AUTH }}
        secrets: |
          STYRA_TOKEN: styra-das-token

    - name: OPA/Rego unit tests
      uses: extenda/actions/styra-das-test@v0
      with:
        policy-type: ${{ inputs.policy-type }}
        permission-prefix: ${{ inputs.system }}
        service-name: ${{ inputs.service-name }}
        styra-das-token: ${{ env.STYRA_TOKEN }}

    - name: Notify Slack if failed
      if: ${{ github.ref == 'refs/heads/master' && failure() && inputs.notify-slack-on-fail }}
      uses: extenda/actions/slack-notify@v0
      with:
        text: |
          *OPA test failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
          Test failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{github.job}}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
        channel: ${{ inputs.slack-channel }}
        service-account-key: ${{ inputs.GCLOUD_AUTH || inputs.SECRET_AUTH }}
