name: 'Test OPA Rules'
description: 'Run tests for opa rules'
inputs:
  SECRET_AUTH:
    description: 'GCP Auth'
    required: true
  GCLOUD_AUTH:
    description: 'GCP Auth (Staging)'
    required: false
  slack-channel:
    description: Name of the channel to notify failing action
    required: true
  notify-slack-on-fail:
    description: 'If true notifies slack channel specified in secrets in case this workflow fails'
    default: false
    type: boolean
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Test OPA policies
      uses: extenda/actions/opa-policy-test@v0
      with:
        service-account-key: ${{ inputs.GCLOUD_AUTH || inputs.SECRET_AUTH }}

    - name: Notify Slack if failed
      if: ${{ github.ref == 'refs/heads/master' && failure() && inputs.notify-slack-on-fail }}
      uses: extenda/actions/slack-notify@v0
      with:
        text: |
          *OPA test failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
          Test failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{github.job}}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
        channel: ${{ inputs.slack-channel }}
        service-account-key: ${{ inputs.GCLOUD_AUTH || inputs.SECRET_AUTH }}
