name: should-i-deploy
description: Check if the current time is Monday to Thursday and within work hours, and fail the workflow if it is not.
inputs:
  time-zone:
    description: 'The time zone to check'
    required: false
    default: 'UTC'
  work-hours-start:
    description: 'The start of the work hours (HH:MM)'
    required: false
    default: '08:00'
  work-hours-end:
    description: 'The end of the work hours (HH:MM)'
    required: false
    default: '17:00'
runs:
  using: composite
  steps:
    - name: Check if it is Monday to Thursday and within work hours
      shell: bash
      run: |
        export TZ="${{ inputs.time-zone }}"
        COMMIT_MSG="${{ github.event.head_commit.message }}"

        if [[ "$COMMIT_MSG" == *"[force deploy]"* ]]; then
          echo "Force deploy detected in commit message. Proceeding..."
          exit 0
        fi

        CURRENT_TIME=$(date +%H:%M)
        DAY_OF_WEEK=$(date +%u)
        # 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday, 7=Sunday
        
        if [ "$DAY_OF_WEEK" -le 4 ]; then
          if [[ "$CURRENT_TIME" > "${{ inputs.work-hours-start }}" || "$CURRENT_TIME" == "${{ inputs.work-hours-start }}" ]] && \
             [[ "$CURRENT_TIME" < "${{ inputs.work-hours-end }}" || "$CURRENT_TIME" == "${{ inputs.work-hours-end }}" ]]; then
            echo "It's a good day and time to deploy!"
            exit 0
          else
            echo "Deployment is only allowed during work hours (${{ inputs.work-hours-start }} - ${{ inputs.work-hours-end }}). Current time is $CURRENT_TIME."
            exit 1
          fi
        else
          echo "Deployment is only allowed Monday to Thursday. Today is $(date +%A)."
          exit 1
        fi
