name: 'Acceptance for MCPE'
description: 'Acceptance action for MCPE services'

inputs:
  gcloud-auth-staging:
    description: 'GCLOUD_AUTH_STAGING value from secrets'
    required: true
  acceptance-mcpe-base-url:
    description: 'Base URL of the service against which to run acceptance tests'
    required: true
  acceptance-mcpe-postman-collection-path:
    description: 'Path to Postman collection'
    required: true
  acceptance-mcpe-postman-environment-path:
    description: 'Path to Postman environment variables'
    required: true
  acceptance-mcpe-globals-path:
    description: 'Path to globals.json'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.gcloud-auth-staging }}
        secrets: |
          TEST_USER_PASSWORD: test_shoppper_password
          TEST_STAFF_USER_PASSWORD: test_user_password
          
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "test/newman/globals.json"
        json: '{ "values": [ { "key": "StoreId", "value": "1", "enabled": true},{ "key": "baseUrl", "value": "${{ inputs.acceptance-mcpe-base-url }}", "enabled": true}, { "key": "testUserPwd", "value": "${{env.TEST_USER_PASSWORD}}", "enabled": true}, { "key": "testStaffUserPwd", "value": "${{env.TEST_STAFF_USER_PASSWORD}}", "enabled": true}] }'
        
    - name: Acceptance tests
      uses: matt-ball/newman-action@0.0.28
      with:
        collection: ${{ inputs.acceptance-mcpe-postman-collection-path }}
        environment: ${{ inputs.acceptance-mcpe-postman-environment-path }}
        globals: ${{ inputs.acceptance-mcpe-globals-path }}