name: Lint pull request title
on:
  workflow_call:
    inputs:
      enable_pr_title_validation:
        description: 'Enable PR title validation according to conventional commits rules.'
        required: false  
        default: false  
        type: boolean 

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint pull request title
        uses: extenda/actions/commitlint@v0
        with:
          message: ${{ github.event.pull_request.title }}
          enable_pr_title_validation: ${{ inputs.enable_pr_title_validation }}

      - name: Lint commit messages
        if: always()
        uses: extenda/actions/commitlint@v0
        with:
          relaxed: ${{ contains(job.status, 'success') }}
