name: Lint pull request title
on:
  workflow_call:
    inputs:
      require-type-and-scope:
        description: 'Require stricter commit message validation enforcing both the type and scope.'
        required: false
        default: 'false'
        type: string
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint pull request title
        uses: extenda/actions/commitlint@v0
        with:
          message: ${{ github.event.pull_request.title }}
          require-type-and-scope: ${{ inputs.require-type-and-scope }}

      - name: Lint commit messages
        if: always()
        uses: extenda/actions/commitlint@v0
        with:
          relaxed: ${{ contains(job.status, 'success') }}
