name: Kafka Streams Lint

on:
  workflow_call:
    secrets:
      SECRET_AUTH:
        required: true
    inputs:
      java-version:
        description: 'The Java version.'
        type: number
        required: false
        default: 21
      jdk-distribution:
        description: 'The JDK distribution.'
        type: string
        required: false
        default: temurin
      working-directory:
        description: 'working directory'
        required: false
        type: string
        default: .

jobs:
  detekt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            GITHUB_TOKEN: github-token
            NEXUS_PASSWORD: nexus-password
            NEXUS_USERNAME: nexus-username

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ inputs.jdk-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Kafka Streams lint
        uses: extenda/shared-workflows/composite-actions/kafka-streams-lint@master
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ inputs.working-directory }}
