name: Stop the service
on:
  workflow_call:
    secrets:
      service-namespace:
        description: 'A namespace of the service in styra'
        required: true
      gcp-project:
        description: 'A project name in gcp'
        required: true
      slack-channel:
        description: 'A slack channel which needs to be notified in case of failure'
        required: false
      SECRET_AUTH:
        required: true
      GCLOUD_AUTH_STAGING:
        required: false
      GCLOUD_AUTH_PROD:
        required: false
    inputs:
      prod:
        description: 'If true stops the service in prod'
        required: true
        type: boolean
      is-statefulset:
        description: 'If true assumes the service is of type statefulset. If false assumes the service is of type deployment. Defaults to false.'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  stop-service:
    name: Stop GKE ${{ inputs.is-statefulset && 'statefulset' || 'deployment' }} in ${{ inputs.prod && 'prod' || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Scale the GKE ${{ inputs.is-statefulset && 'statefulset' || 'deployment' }} to 0 replicas
        uses: extenda/shared-workflows/composite-actions/pnp-gke-service-control@master
        with:
          operation: scale
          replicas: '0'
          service-namespace: ${{ secrets.service-namespace }}
          gcp-project: ${{ secrets.gcp-project }}
          is-statefulset: ${{ inputs.is-statefulset }}
          service-account-key: ${{ inputs.prod && secrets.GCLOUD_AUTH_PROD || secrets.GCLOUD_AUTH_STAGING }}
          slack-channel: ${{ secrets.slack-channel }}
          slack-service-account-key: ${{ secrets.SECRET_AUTH }}
