name: test and build docker image

on:
  workflow_call:
    secrets:
      SECRET_AUTH:
        required: true
      GCLOUD_AUTH_STAGING:
        required: true          
    inputs:
      GCR_image_name:
        description: 'A name of the image to be created in GCR'
        required: true
        type: string
      path-to-pom:
        description: 'Path to the pom file'
        required: true
        type: string
      path-to-dockerfile:
        description: 'Path to dockerfile which builds the service.'
        required: true
        type: string
      slack-channel:
        description: 'A slack channel which needs to be notified in case of failure'
        required: false
        type: string
      pact-application-id:
        required: false
        type: string
      pact-webhook-id:
        required: false
        type: string        
      jdk-distribution:
        description: 'JDK Distribution name'
        type: string
        required: false
        default: 'temurin'
      java-version:
        description: 'Java version used in the project'
        type: string
        required: false
        default: '17'
      use-old-setup-java:
        description: 'If true uses the java setup step of version 1'
        type: boolean
        required: false
        default: false
      do-pact-consumer-tests:
        description: 'If true runs tests defining data contracts'
        type: boolean
        required: false
        default: false
      do-pact-provider-tests:
        description: 'If true runs tests verifying implementation against data-contracts'
        type: boolean
        required: false
        default: false
      is-pact-consumer-can-i-deploy-dry-run:
        description: 'If true, consumer can-i-deploy step will be executed in dry-run mode'
        type: boolean
        required: false
        default: false
      is-pact-provider-can-i-deploy-dry-run:
        description: 'If true, provider can-i-deploy step will be executed in dry-run mode'
        type: boolean
        required: false
        default: false
      native-image:
        description: 'If true uses the GraalVm to compile app'
        type: boolean
        required: false
        default: false
      enable-kafka-streams-lint:
        description: 'If true runs Kafka Streams Lint'
        type: boolean
        required: false
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            GITHUB-TOKEN: github-token
            NEXUS_PASSWORD: nexus-password
            NEXUS_USERNAME: nexus-username

      - name: Set up JDK
        if: ${{ inputs.use-old-setup-java == false }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.jdk-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Set up JDK
        if: ${{ inputs.use-old-setup-java == true }}
        uses: actions/setup-java@v1
        with:
          distribution: ${{ inputs.jdk-distribution }}
          java-version: ${{ inputs.java-version }}

      - uses: actions/cache@v4
        if: ${{ inputs.use-old-setup-java == true }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Determine version
        uses: extenda/actions/conventional-version@v0
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-number: ${{ github.run_number }}

      - name: Verify with Maven        
        uses: extenda/actions/maven@v0
        with:
          args: verify -s settings.xml
          version: ${{ steps.semver.outputs.version }}-SNAPSHOT
          service-account-key: ${{ secrets.SECRET_AUTH }}

      - name: Kafka Streams lint - fetch detekt config file
        if: ${{ inputs.enable-kafka-streams-lint == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            curl -sSL \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            "https://api.github.com/repos/extenda/shared-workflows/contents/.github/configs/pnp-detekt-plugin.yml" \
            -o pnp-detekt-plugin.yml

            cat pnp-detekt-plugin.yml

      - name: Kafka Streams lint - get Detekt plugin for kafka streams
        if: ${{ inputs.enable-kafka-streams-lint == true }}
        uses: extenda/actions/maven@v0
        with:
          args: dependency:get -Dartifact=com.retailsvc:pnp-processors-core-common:0.140.3:jar
          service-account-key: ${{ secrets.SECRET_AUTH }}
          
      
      - name: Kafka Streams lint - build classpath with maven
        if: ${{ inputs.enable-kafka-streams-lint == true }}
        uses: extenda/actions/maven@v0
        with:
          args: dependency:build-classpath -DincludeScope=runtime -Dmdep.outputFile=cp.txt -DexcludeGroupIds=org.jetbrains.kotlin -DexcludeArtifactIds=kotlin-compiler-embeddable -q
          service-account-key: ${{ secrets.SECRET_AUTH }}
          

      - name: Kafka Streams lint - build classpath lib dir with maven
        if: ${{ inputs.enable-kafka-streams-lint == true }}
        uses: extenda/actions/maven@v0
        with:
          args: dependency:copy-dependencies -DoutputDirectory=lib -DexcludeGroupIds=org.jetbrains.kotlin -DexcludeArtifactIds=kotlin-compiler-embeddable -q
          service-account-key: ${{ secrets.SECRET_AUTH }}
          

      - name: Kafka Streams lint - download Detekt CLI
        if: ${{ inputs.enable-kafka-streams-lint == true }}
        run: |
          curl -s -L --create-dirs -o lib/detekt-cli.jar \
            https://github.com/detekt/detekt/releases/download/v1.23.8/detekt-cli-1.23.8-all.jar
      

      - name: Kafka Streams lint - verify with Detekt
        if: ${{ inputs.enable-kafka-streams-lint == true }}
        run: |
          java -cp "target/classes:lib/*" \
            io.gitlab.arturbosch.detekt.cli.Main \
              --input  src/main/kotlin \
              --config  pnp-detekt-plugin.yml \
              --classpath "target/classes:$(cat cp.txt)" \
              --jvm-target 21 \
              --plugins ~/.m2/repository/com/retailsvc/pnp-processors-core-common/0.140.3/pnp-processors-core-common-0.140.3.jar \

      - name: Analyze with Sonar
        uses: extenda/actions/sonar-scanner@v0
        with:
          sonar-host: https://sonarcloud.io
          maven-args: --file ${{ inputs.path-to-pom }} --settings settings.xml org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
          service-account-key: ${{ secrets.SECRET_AUTH }}
          
      - uses: graalvm/setup-graalvm@v1
        if: ${{ inputs.native-image == true }}
        with:
          distribution: 'graalvm'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Package native image
        if: ${{ inputs.native-image == true }}
        uses: extenda/actions/maven@v0
        with:
          args: verify -Dpackaging=native-image -s settings.xml
          version: ${{ steps.semver.outputs.version }}-SNAPSHOT
          service-account-key: ${{ secrets.SECRET_AUTH }}
    
      - name: Publish pacts
        if: ${{ inputs.do-pact-consumer-tests == true }}
        uses: extenda/actions/pact-publish@v0
        with:
          pacts-directory: target/pacts
          service-account-key: ${{ secrets.SECRET_AUTH }}

      - name: Can i deploy - consumer?
        if: ${{ inputs.do-pact-consumer-tests == true }}
        uses: extenda/actions/pact-can-i-deploy@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          application-name: ${{ inputs.pact-application-id }}
          retry-while-unknown: 15
          retry-interval: 10
          dry-run: ${{ inputs.is-pact-consumer-can-i-deploy-dry-run }}
          env: "staging"

      - name: Can i deploy - provider?
        if: ${{ inputs.do-pact-provider-tests == true }}
        uses: extenda/actions/pact-can-i-deploy@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          application-name: ${{ inputs.pact-application-id }}
          retry-while-unknown: 15
          retry-interval: 10
          dry-run: ${{ inputs.is-pact-provider-can-i-deploy-dry-run }}
          env: "staging"

      - name: Setup gcloud
        if: github.ref == 'refs/heads/master'
        uses: extenda/actions/setup-gcloud@v0
        id: gcloud
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH_STAGING }}

      - name: Authenticate docker
        if: github.ref == 'refs/heads/master'
        run: |
          gcloud --quiet auth configure-docker

      - name: Docker build and push
        if: github.ref == 'refs/heads/master'
        run: |
          IMAGE=eu.gcr.io/extenda/${{ inputs.GCR_image_name }}
          docker build . -f ${{ inputs.path-to-dockerfile }} --build-arg jar_version=${{ steps.semver.outputs.version }} -t $IMAGE:${{ steps.semver.outputs.version }} -t $IMAGE:${{ github.sha }} -t $IMAGE:latest
          docker push --all-tags $IMAGE

      - name: Attest image
        if: github.ref == 'refs/heads/master'
        uses: extenda/actions/binary-auth-attestation@v0
        with:
          image-path: eu.gcr.io/extenda/${{ inputs.GCR_image_name }}
          service-account-key: ${{ secrets.GCLOUD_AUTH_STAGING }}

      - name: Notify Slack if failed
        if: ${{ failure() && github.ref == 'refs/heads/master' }}
        uses: extenda/actions/slack-notify@v0
        with:
          text: |
            *Build failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Build failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{github.job}}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ inputs.slack-channel }}
          service-account-key: ${{ secrets.SECRET_AUTH }}
