name: deploy-k8s-service

on:
  workflow_call:
    secrets:
      GCR_image_name:
        description: 'A name of the image to be created in GCR'
        required: true
      slack-channel:
        description: 'A slack channel which needs to be notified in case of failure'
        required: false
      SECRET_AUTH:
        required: true
      GCLOUD_AUTH:
        required: true
      dora-component:
        description: 'Dora component name'
        required: true
      pact-application-id:
        required: false
    inputs:
      service-definition:
        description: 'Path to kubernetes config file.'
        type: string
        required: true
      do-pact-consumer-tests:
        description: 'If true runs tests defining data contracts'
        type: boolean
        required: false
        default: false
      release-version:
        description: 'deploy release version'
        type: boolean
        required: false
        default: false
      tag-prefix:
        description: 'Release tag prefix. Must be provided in case of multiple projects in the same repository. Each project needs to have its own prefix. Use {service-name}-v format.'
        type: string
        required: false
        default: 'v'
      workflow-env-vars:
        description: 'key/value pairs separated by commas to pass as deploy environment variables'
        type: string
        required: false
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            GITHUB-TOKEN: github-token
            PACT_BROKER_USERNAME: pact-broker-username
            PACT_BROKER_PASSWORD: pact-broker-password
            JIRA_USERNAME: jira-username
            JIRA_PASSWORD: jira-password
      
      - name: Determine version
        uses: extenda/actions/conventional-version@v0
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-number: ${{ github.run_number }}
          tag-prefix: ${{ inputs.tag-prefix }}

      - name: Deploy to Autopilot staging
        if: ${{ inputs.release-version == false }}
        uses: extenda/actions/cloud-deploy@feat/EA-2106
        with:
          secrets-account-key: ${{ secrets.SECRET_AUTH }}
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          service-definition: ${{ inputs.service-definition }}
          image: eu.gcr.io/extenda/${{ secrets.GCR_image_name }}:${{ steps.semver.outputs.release-version }}
          update-dns: always
          workflow-env-vars: ${{ inputs.workflow-env-vars }}


      - name: Deploy to Autopilot prod
        if: ${{ inputs.release-version == true }}
        uses: extenda/actions/cloud-deploy@feat/EA-2106
        with:
          secrets-account-key: ${{ secrets.SECRET_AUTH }}
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          service-definition: ${{ inputs.service-definition }}
          image: eu.gcr.io/extenda/${{ secrets.GCR_image_name }}:${{ steps.semver.outputs.release-version }}
          update-dns: always
          workflow-env-vars: ${{ inputs.workflow-env-vars }}

      - name: Dora Component
        if: ${{ inputs.release-version == true }}
        uses: extenda/actions/dora-metrics@v0
        with:
          product-name: Product And Price
          product-component: ${{ secrets.dora-component }}
          jira-username: ${{ env.JIRA_USERNAME }}
          jira-password: ${{ env.JIRA_PASSWORD }}
          jira-project-key: EA

      - name: PACT record deployment 
        if: ${{ inputs.do-pact-consumer-tests == true }}
        uses: extenda/actions/pact-record-deployment@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          application-name: ${{ secrets.pact-application-id }}
          release-version: ${{ github.sha }}

      - name: Notify Slack if failed
        if: failure()
        uses: extenda/actions/slack-notify@v0
        with:
          text: |
            *Build failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Build failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{github.job}}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ secrets.slack-channel }}
          service-account-key: ${{ secrets.SECRET_AUTH }}
      
 