name: Print Kafka Stream Topology To Readme
on:
  workflow_call:

jobs:
  update-readme-topology:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Update README
        run: .github/workflows/script/generate-mermaid/main.mjs

      - name: Configure Git
        uses: extenda/actions/setup-git@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Commit and Push Changes
        run: |
          git add .
          git -c user.name="Extenda-DevOps-Bot" -c user.email="devops_team@extenda.se" commit -S -m "Update README topology"
          git push origin HEAD:${{ github.ref }}
