name: Pull Request
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/my-action
