name: Pull Request
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  commitlint:
    uses: extenda/shared-workflows/.github/workflows/common-commitlint.yml@feature/introduce_reusable_workflow
