name: Pull Request
on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release
        uses: extenda/actions/conventional-release@v0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release branch
        run: |
          releaseBranch=$(echo "${{ steps.release.outputs.release-tag }}" | tr "." " " | awk '{print $1}')
          git checkout -B $releaseBranch ${{ steps.release.outputs.release-tag }}
          git config --add user.name "GitHub Actions"
          git config --add user.email devops@extendaretail.com
          git push origin $releaseBranch --force
