name: 'Acceptance action for lossprevention services'
on: 
  workflow_call:
    inputs: 
      secret-auth:
        description: 'SECRET_AUTH value from secrets'
        type: string
        required: true
      gcloud-auth:
        description: 'GCLOUD_AUTH_STAGING/GCLOUD_AUTH_PROD value from secrets based on the environment'
        type: string
        required: true
      collection:
        description: 'Collection to use'
        type: string
        required: true
        default: './slp/tests/acceptance/integration_test.postman_collection.json'
      environment:
        description: 'Environment to use'
        type: string
        required: true
        default: './slp/tests/acceptance/integration_test.staging.postman_environment.json'
jobs: 
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secrets
        uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ inputs.secret-auth }}
          secrets: |
            GITHUB-TOKEN: github-token

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: extenda/selfservice-lossprevention-common
          path: 'slp'
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set up GCloud
        uses: extenda/actions/setup-gcloud@v0
        id: gcloud
        with:
          service-account-key: ${{ inputs.gcloud-auth }}

      - name: Identity token
        uses: extenda/actions/identity-token@v0
        with:
          service-account-key: ${{ inputs.gcloud-auth }}
          service-account: basketauditfrontend@${{ steps.gcloud.outputs.project-id }}.iam.gserviceaccount.com
          audiences: basketauditfrontend

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Accceptance tests
        run: |
          npm install newman --no-save --silent
          npx newman run ${{ inputs.collection }} \
            --environment ${{ inputs.environment }} \
            --env-var iamToken=$IDENTITY_TOKEN
