on:
  workflow_call:
    secrets:
      secret-auth:
        description: 'SECRET_AUTH value from secrets'
        required: true
      gcloud-auth-staging:
        description: 'GCLOUD_AUTH_STAGING value from secrets'
        required: true
      gcloud-auth-prod:
        description: 'GCLOUD_AUTH_PROD value from secrets'
        required: true
    inputs:
      gcr-image-name:
        description: |
          Google Container Registry Docker image name
        type: string
        required: true
      service-name:
        description: |
          Service name in GCP
        type: string
        required: true
      dockerfile-path:
        description: |
          Path to Dockerfile
        type: string
        required: true
      system-name:
        description: |
          System name (sng or mcp)
        type: string
        required: true
      use-acceptance:
        description: |
          Use acceptance
        type: boolean
        required: true
      acceptance-base-url:
        description: |
          Base URL of the service against which to run acceptance tests. Must be set when 'use-acceptance' is 'true'
        type: string
        required: true
      acceptance-postman-collection-path:
        description: |
          Path to Postman collection. Must be set when 'use-acceptance' is 'true'
        type: string
        required: true
      acceptance-postman-environment-path:
        description: |
          Path to Postman environment variables. Must be set when 'use-acceptance' is 'true'
        type: string
        required: true
      acceptance-globals-path:
        description: |
          Path to globals.json. Must be set when 'use-acceptance' is 'true'
        type: string
        required: true
      release-name:
        type: string
        required: true
      product-name:
        type: string
        required: true
      product-component:
        type: string
        required: true
      jira-project-key:
        type: string
        required: true
      slack-channel:
        description: Name of the channel to notify failing action
        required: false
        default: selfscan-pipeline-notifications
        type: string
      code-freeze:
        description: |
            Code freeze flag. Use this flag when there is a code freeze and code changes should not be deployed to staging and production environments.
        type: boolean
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extenda/actions/opa-policy-test@v0
        with:
          service-account-key: ${{ secrets.gcloud-auth-staging }}

      - name: Notify Slack if validate fails
        uses: extenda/actions/slack-notify@v0
        if: failure() && github.ref == 'refs/heads/master'
        with:
          text: |
            *Validate failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Validate failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{ github.job }}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ inputs.slack-channel }}
          service-account-key: ${{ secrets.secret-auth }}

  staging:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name:  Code freeze check
        run: |
          if [[ "${{ inputs.code-freeze }}" == "true" && "${{ github.event.head_commit.message }}" != *"[force-deploy]"* ]]; then
            echo "Code freeze flag is enabled. Skipping deployment.";
            echo "To trigger a deployment that bypasses the code-freeze input checks, include '[force-deploy]' in the commit message.";
            exit 1
          else
            echo "Code freeze is not enabled. Proceeding with deployment."
          fi

      - name: Build Docker image
        uses: extenda/shared-workflows/composite-actions/docker-build@master
        with:
          gcloud-auth-staging: ${{ secrets.gcloud-auth-staging }}
          dockerfile-path: ${{ inputs.dockerfile-path }}
          gcr-image-name: ${{ inputs.gcr-image-name }}

      - name: Deploy to staging
        uses: extenda/actions/cloud-deploy@v0
        with:
          secrets-account-key: ${{ secrets.secret-auth }}
          service-account-key: ${{ secrets.gcloud-auth-staging }}
          image: eu.gcr.io/extenda/${{ inputs.gcr-image-name }}:${{ github.sha }}
          update-dns: always

      - name: Notify Slack if staging fails
        uses: extenda/actions/slack-notify@v0
        if: failure()
        with:
          text: |
            *Staging failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Staging failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{ github.job }}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ inputs.slack-channel }}
          service-account-key: ${{ secrets.secret-auth }}

  acceptance:
    if: ${{ inputs.use-acceptance }}
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ inputs.acceptance-globals-path }}
          json: '{ "values": [ { "key": "baseUrl", "value": "${{ inputs.acceptance-base-url }}", "enabled": true}] }'

      - name: Acceptance tests
        uses: matt-ball/newman-action@0.0.28
        with:
          collection: ${{ inputs.acceptance-postman-collection-path }}
          environment: ${{ inputs.acceptance-postman-environment-path }}
          globals: ${{ inputs.acceptance-globals-path }}

      - name: Notify Slack if acceptance fails
        uses: extenda/actions/slack-notify@v0
        if: failure()
        with:
          text: |
            *Acceptance failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Acceptance failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{ github.job }}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ inputs.slack-channel }}
          service-account-key: ${{ secrets.secret-auth }}
  
  release:
    if: |
      always() &&
      (needs.acceptance.result == 'success' || needs.acceptance.result == 'skipped') &&
      (needs.staging.result == 'success')
    runs-on: ubuntu-latest
    needs: [staging, acceptance]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.secret-auth }}
          secrets: |
            GITHUB-TOKEN: github-token

      - name: Create release
        uses: extenda/actions/conventional-release@v0
        id: semver
        with:
          name: ${{ inputs.release-name }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB-TOKEN }}

      - uses: extenda/actions/setup-gcloud@v0
        with:
          service-account-key: ${{ secrets.gcloud-auth-prod }}

      - name: Add tag in GCR
        run: |
          gcloud container images add-tag \
            eu.gcr.io/extenda/${{ inputs.gcr-image-name }}:${{ github.sha }} \
            eu.gcr.io/extenda/${{ inputs.gcr-image-name }}:${{ steps.semver.outputs.release-tag }}

      - name: Notify Slack if release fails
        uses: extenda/actions/slack-notify@v0
        if: failure()
        with:
          text: |
            *Release failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Release failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{ github.job }}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ inputs.slack-channel }}
          service-account-key: ${{ secrets.secret-auth }}

  deploy:
    if: |
      always() &&
      (needs.acceptance.result == 'success' || needs.acceptance.result == 'skipped') &&
      (needs.release.result == 'success' || needs.release.result == 'skipped') &&
      (needs.staging.result == 'success')
    runs-on: ubuntu-latest
    needs: [staging, acceptance, release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.secret-auth }}
          secrets: |
            JIRA_USERNAME: jira-username
            JIRA_PASSWORD: jira-password
            STYRA_TOKEN: styra-das-token

      - uses: extenda/actions/conventional-version@v0
        id: semver

      - uses: extenda/actions/setup-gcloud@v0
        id: gcloud
        with:
          service-account-key: ${{ secrets.gcloud-auth-prod }}

      - name: Deploy to Styra DAS Production
        uses: extenda/actions/styra-das-deploy@v0
        with:
          styra-das-token: ${{ env.STYRA_TOKEN }}
          permission-prefix: ${{ inputs.system-name }}
          service-name: ${{ inputs.service-name }}

      - name: Deploy to production
        uses: extenda/actions/cloud-deploy@v0
        with:
          secrets-account-key: ${{ secrets.secret-auth }}
          service-account-key: ${{ secrets.gcloud-auth-prod }}
          image: eu.gcr.io/extenda/${{ inputs.gcr-image-name }}:${{ steps.semver.outputs.release-tag }}
          update-dns: always

      - uses: extenda/actions/dora-metrics@v0
        with:
          product-name: ${{ inputs.product-name }}
          product-component: ${{ inputs.product-component }}
          jira-username: ${{ env.JIRA_USERNAME }}
          jira-password: ${{ env.JIRA_PASSWORD }}
          jira-project-key: ${{ inputs.jira-project-key }}

      - name: Notify Slack if deploy fails
        uses: extenda/actions/slack-notify@v0
        if: failure()
        with:
          text: |
            *Deploy failed for ${{ github.repository }}: ${{ github.workflow }}* :heavy_exclamation_mark:
            Deploy failed on ${{ github.event_name }} event. Workflow: ${{ github.workflow }}. Job: ${{ github.job }}. Run id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>
          channel: ${{ inputs.slack-channel }}
          service-account-key: ${{ secrets.secret-auth }}